export const Typography = ({ colors, fontFamily }) => {

    return {
        fontFamily: fontFamily,
        fontWeightRegular: 400,
        fontWeightMedium: 600,
        fontWeightBold: 700,
        h1: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "140%",
            fontSize: '32px',
            fontStyle: "normal",
        },
        h2: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "64px",
            fontSize: '40px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
        },
        h3: {
            color: colors?.primary?.main,
            fontWeight: 500,
            fontSize: "14px",
            fontStyle: "normal",
            lineHeight: "140%",
            letterSpacing: "0.2px",
            transition: 'ease 0.4s',
        },
        h4: {
            color: colors?.grey[300],
            fontWeight: 500,
            lineHeight: "140%",
            fontSize: '12px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
            letterSpacing: "0.13px",
        },
        h5: {
            color: colors?.text?.dark,
            fontWeight: 400,
            lineHeight: "16px",
            fontSize: '13px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
        },
        h6: {
            color: colors?.common?.black,
            fontWeight: 500,
            lineHeight: "64px",
            fontSize: '10px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
        },
        subtitle1: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "24px",
            fontSize: '14px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
        },
        subtitle2: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "64px",
            fontSize: '15px',
            fontStyle: "normal",
        },
        body: {
            color: colors?.grey?.greyDark,
            fontWeight: 600,
            fontSize: "12px",
            fontStyle: "normal",
            lineHeight: "140%",
            letterSpacing: "0.1px",
            transition: 'ease 0.4s',
        },
        body1: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "64px",
            fontSize: '48px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
        },
        body2: {
            lineHeight: 22 / 14,
            fontSize: 12,
            transition: 'ease 0.4s',
        },
        caption: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "64px",
            fontSize: '48px',
            fontStyle: "normal",
            transition: 'ease 0.4s',
        },
        overline: {
            color: colors?.text?.dark,
            fontWeight: 600,
            fontSize: '20px',
            fontStyle: "normal",
            lineHeight: "32px",
            letterSpacing: "-0.4px",
            textTransform: "capitalize",

        },
        button: {
            color: colors?.text?.dark,
            fontWeight: 700,
            lineHeight: "64px",
            fontSize: '48px',
            fontStyle: "normal",
            textTransform: "capitalize",
            transition: 'ease 0.4s',
        },


    };

}
